<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>060acddd-9ac9-4709-869a-d4f13615ee12</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Pages\Admin\Tabs\**" />
    <Content Remove="Components\Pages\Admin\Tabs\**" />
    <EmbeddedResource Remove="Components\Pages\Admin\Tabs\**" />
    <None Remove="Components\Pages\Admin\Tabs\**" />
    <Compile Remove="artifacts\**" />
    <Content Remove="artifacts\**" />
    <EmbeddedResource Remove="artifacts\**" />
    <None Remove="artifacts\**" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Blazored.Toast" Version="4.2.1" />
    <PackageReference Include="Auth0.AspNetCore.Authentication" Version="1.7.0" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.7" />
		<PackageReference Include="MudBlazor" Version="9.4.0" />
		<PackageReference Include="Refit" Version="8.0.0" />
		<PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />

	</ItemGroup>

</Project>
